services:
  postgres:
    image: 'postgres:15.2-alpine'
    environment:
      - 'POSTGRES_DB=modulith_dojo'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
    driver: local
