services:
  postgres:
    image: 'postgres:15.2-alpine'
    environment:
      - 'POSTGRES_DB=modulith_dojo'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  rabbitmq:
    image: 'rabbitmq:3.12-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
