spring:
  application:
    name: modulith-dojo
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/modulith_dojo
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com:
      fusionhs: INFO
    org:
      flywaydb: DEBUG 