spring:
  application:
    name: modulith-dojo
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com:
      fusionhs: INFO
    org:
      hibernate:
        SQL: DEBUG 